<?php
/**
 * @file
 * Code for the Negawatt electricity storage feature.
 */

include_once 'negawatt_electricity.features.inc';

/**
 * Implements hook_entity_info().
 */
function negawatt_electricity_entity_info() {
  $return = array(
    'electricity' => array(
      'label' => t('Electricity data', array(), array('context' => 'electricity entity')),
      'locking mode' => 'pessimistic',
      'base table' => 'negawatt_electricity_normalized',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'entity class' => 'Electricity',
      'controller class' => 'EntityAPIController',
      'metadata controller class' => 'ElectricityMetadataController',
      'views controller class' => 'EntityDefaultViewsController',
      'entity cache' => module_exists('entitycache'),
    ),

    'electricity_raw' => array(
      'label' => t('Electricity raw data', array(), array('context' => 'electricity raw entity')),
      'base table' => 'negawatt_electricity',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'entity class' => 'ElectricityRaw',
      'controller class' => 'EntityAPIController',
      'metadata controller class' => 'ElectricityRawMetadataController',
      'views controller class' => 'EntityDefaultViewsController',
      'entity cache' => module_exists('entitycache'),
    ),
  );

  return $return;
}

/**
 * Returns auction controller.
 *
 * @return AuctionEntityController
 */
function negawatt_electricity_get_controller() {
  return entity_get_controller('electricity');
}
