<?php
/**
 * @file
 * Code for the Negawatt electricity storage feature.
 */

include_once 'negawatt_electricity.features.inc';



/**
 * Implements hook_cron().
 */
function negawatt_data_cron() {

}

/**
 * Implements hook_entity_info().
 */
function negawatt_electricity_entity_info() {
  $return = array(
    'electricity' => array(
      'label' => t('Electricity data', array(), array('context' => 'electricity entity')),
      'controller class' => 'ElectricityEntityController',
      'locking mode' => 'pessimistic',
      'base table' => 'negawatt_electricity_normalized',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'access arguments' => array(
        'user key' => 'uid',
        'access tag' => 'electricity_access',
      ),
      'permission labels' => array(
        'singular' => t('electricity'),
        'plural' => t('electricity'),
      ),
      'metadata controller class' => 'EntityDefaultMetadataController',
      'views controller class' => 'EntityDefaultViewsController',
      'entity cache' => module_exists('entitycache'),
      'metadata controller class' => 'ElectricityMetadataController',
    ),
    'electricity_raw' => array(
      'label' => t('Electricity raw data', array(), array('context' => 'electricity raw entity')),
      'controller class' => 'ElectricityRawEntityController',
      'locking mode' => 'pessimistic',
      'base table' => 'negawatt_electricity',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'access arguments' => array(
        'user key' => 'uid',
        'access tag' => 'electricity_raw_access',
      ),
      'permission labels' => array(
        'singular' => t('electricity raw'),
        'plural' => t('electricity raw'),
      ),
      'metadata controller class' => 'EntityDefaultMetadataController',
      'views controller class' => 'EntityDefaultViewsController',
      'entity cache' => module_exists('entitycache'),
      'metadata controller class' => 'ElectricityRawMetadataController',
    ),
  );

  return $return;
}

/**
 * Returns auction controller.
 *
 * @return AuctionEntityController
 */
function negawatt_electricity_get_controller() {
  return entity_get_controller('electricity');
}