<?php
/**
 * @file
 * Code for the Negawatt climate storage feature.
 */

include_once 'negawatt_climate.features.inc';

/**
 * Implements hook_entity_info().
 */
function negawatt_climate_entity_info() {
  $return = array(
    'climate' => array(
      'label' => t('Climate data', array(), array('context' => 'climate entity')),
      'locking mode' => 'pessimistic',
      'base table' => 'negawatt_climate_normalized',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'entity class' => 'Climate',
      'controller class' => 'EntityAPIController',
      'metadata controller class' => 'ClimateMetadataController',
      'views controller class' => 'EntityDefaultViewsController',
      'entity cache' => module_exists('entitycache'),
    ),

    'climate_raw' => array(
      'label' => t('Climate raw data', array(), array('context' => 'climate raw entity')),
      'base table' => 'negawatt_climate',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'entity class' => 'ClimateRaw',
      'controller class' => 'EntityAPIController',
      'metadata controller class' => 'ClimateRawMetadataController',
      'views controller class' => 'EntityDefaultViewsController',
      'entity cache' => module_exists('entitycache'),
    ),
  );

  return $return;
}

/**
 * Returns climate controller.
 *
 * @return ClimateEntityController
 */
function negawatt_climate_get_controller() {
  return entity_get_controller('climate');
}
