<?php
/**
 * @file
 * Code for the IEC feature.
 */

include_once 'iec.features.inc';
require_once __DIR__ . '/../../../libraries/geocoder/src/autoload.php';

/**
 * Implements hook_node_presave().
 *
 * Find if there is already an IEC meter with the same contract ID, and if so reference the newly created one, with
 * the original one, which always has the lowest node ID.
 */
function iec_node_presave($node) {
  // Check and update Geocode, if needed.
  iec_node_update_geocode($node);

  if (!empty($node->nid)) {
    // Node is already saved.
    return;
  }

  if ($node->type != 'iec_meter') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);

  if ($wrapper->field_parent_contract->value()) {
    // Parent is already populated.
    return;
  }

  $contract_id = $wrapper->field_contract_id->value();

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'iec_meter')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_contract_id', 'value', $contract_id)
    ->propertyOrderBy('nid', 'ASC')
    ->range(0, 1)
    ->execute();

  if (empty($result['node'])) {
    // This is the first contract ID saved.
    return;
  }

  $nid = key($result['node']);
  $wrapper->field_parent_contract->set($nid);
}

// Check and update Geocode, if needed.
function iec_node_update_geocode($node) {
  // Make sure wer'e dealing with an iec-meter.
  if ($node->type != 'iec_meter') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper_original = entity_metadata_wrapper('node', $node->original);

  // Check if address field was changed.
  if ($node->is_new ||
      $wrapper->field_place_address->value() != $wrapper_original->field_place_address->value() ||
      $wrapper->field_place_locality->value() != $wrapper_original->field_place_locality->value()) {

    // Prepare geocoder as static.
    static $adapter  = null;
    static $provider = null;
    static $geocoder = null;
    $adapter = $adapter ? $adapter : new \Geocoder\HttpAdapter\CurlHttpAdapter();
    $provider = $provider ? $provider : new \Geocoder\Provider\GoogleMapsProvider($adapter);
    $geocoder = $geocoder ? $geocoder : new \Geocoder\Geocoder($provider);

    // Look for geocode.
    $street_addr = $wrapper->field_place_address->value();
    $city = $wrapper->field_place_locality->value();
    $full_address = $street_addr . ', ' . $city;
    $success = TRUE;
    try {
      $geocode = $geocoder->geocode($full_address);
      // Geocoding on full address succeeded, set geocode-valid field.
      $wrapper->field_geocode_valid->set(TRUE);
    }
    catch (Exception $e) {
      // Geolocating on full address failed, try locating on city name only.
      drupal_set_message(t('לא ניתן היה לאתר את הכתובת "@address"', array('@address' => $full_address)), 'warning');
      $wrapper->field_geocode_valid->set(FALSE);
      try {
        $geocode = $geocoder->geocode($city);
      }
      catch (Exception $e) {
        // Geolocation failed.
        drupal_set_message(t('לא ניתן היה לאתר את העיר "@address"', array('@address' => $city)), 'warning');
        $success = FALSE;
      }
    }
    if ($success) {
      // Set location field, only if geolocation succeeded.
      $lat = +$geocode->getLatitude();
      $lng = +$geocode->getLongitude();
      $wrapper->field_location->set(array(
        'lat' => $lat,
        'lng' => $lng,
        // @fixme: use geolocation_field_presave() in stead of hard code calculations.
        'lat_sin' => sin(deg2rad($lat)),
        'lat_cos' => cos(deg2rad($lat)),
        'lng_rad' => deg2rad($lng),
      ));
    }
    $wrapper->field_address->set(array(
      'thoroughfare' => $street_addr,
      'locality' => $city,
      'country' => $geocode->getCountryCode(),
    ));
  }
}
