<?php

if (!drupal_is_cli()) {
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Credentials: true');
  header('Access-Control-Allow-Headers: Authorization, access-token');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function negawatt_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful' || $module == 'entity_validator') {
    return 'plugins/' . $plugin;
  }
}
