<?php

/**
 * @file
 * Populate dummy Negawatt content.
 */

/**
 * Implements hook_migrate_api().
 */
function negawatt_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'NegawattAccountMigrate',
    'NegawattIecMeterMigrate',
    'NegawattSatecMeterMigrate',

    // Custom entities.
    'NegawattElectricityMigrate',
    'NegawattElectricityRawMigrate',

    // Vocabulary
    'NegawattMeterCategoryTermsMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
